// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3-GHwO7zzkxg4PFoB8FCjUBEdmzDk5bc',
    appId: '1:538499252909:web:671b4dec8e33867395fc24',
    messagingSenderId: '538499252909',
    projectId: 'the-pantry-a6b26',
    authDomain: 'the-pantry-a6b26.firebaseapp.com',
    storageBucket: 'the-pantry-a6b26.appspot.com',
    measurementId: 'G-HSQW09ZDCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEBfhcTDwLO0ryhqecvPn05jzOEpE5pEk',
    appId: '1:538499252909:android:8cdf41de42fa9d6495fc24',
    messagingSenderId: '538499252909',
    projectId: 'the-pantry-a6b26',
    storageBucket: 'the-pantry-a6b26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg09XsqtRcz1JbnycFaJKJjkwuBbwnoQY',
    appId: '1:538499252909:ios:19eb0586880412a195fc24',
    messagingSenderId: '538499252909',
    projectId: 'the-pantry-a6b26',
    storageBucket: 'the-pantry-a6b26.appspot.com',
    androidClientId: '538499252909-jtcuaoa80g56lm5k2ku3p64h12omsqcd.apps.googleusercontent.com',
    iosClientId: '538499252909-bo4gdugld6bvhilcdv5a6878nrk29usd.apps.googleusercontent.com',
    iosBundleId: 'com.tomsitter.thepantry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg09XsqtRcz1JbnycFaJKJjkwuBbwnoQY',
    appId: '1:538499252909:ios:19eb0586880412a195fc24',
    messagingSenderId: '538499252909',
    projectId: 'the-pantry-a6b26',
    storageBucket: 'the-pantry-a6b26.appspot.com',
    androidClientId: '538499252909-jtcuaoa80g56lm5k2ku3p64h12omsqcd.apps.googleusercontent.com',
    iosClientId: '538499252909-bo4gdugld6bvhilcdv5a6878nrk29usd.apps.googleusercontent.com',
    iosBundleId: 'com.tomsitter.thepantry',
  );
}
