name: firestore_pantry_api
description: A Firestore implementation of the PantryApi.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pantry_api:
    path: ../pantry_api
  equatable: ^2.0.3
  cloud_firestore: ^3.1.0
  firebase_core: ^1.5.0
  meta: ^1.3.0
  rxdart: ^0.27.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0